<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
  </ItemGroup>

</Project>